[package]
name = "ieee80211"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
eui48 = "0.4.6"
bytes = "0.4.12"

[dev-dependencies]
criterion = "0.3.0"


[features]
"serde" = ["eui48/serde"]

[[bench]]
name = "main_benchmark"
harness = false
