[package]
name = "packet"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
eui48 = "0.4.1"

[dev-dependencies]
criterion = "0.2.8"


[[bench]]
name = "main_benchmark"
harness = false
